---
title: Stackbit Azimuth Theme
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Miles Food Truck
  logo_img: ''
  has_nav: true
  menu:
    actions: []
footer:
  logo_img: "/images/Miles Food Truck.png"
  tagline: Miles Food Truck
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our daily meals deals .
  content: Designed by Samanpreet Kaur &copy; Stackbit. All rights reserved.
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
